resolver: lts-19.20

packages:
  - stellar-horizon
  - veche-web
  - yesod-auth-stellar

extra-deps:
  # stellar-horizon:exe
    - github: cblp/servant-cli
      commit: ae3f88791806b3bb9a43173c0758af7c73b36e43
      # https://github.com/mstksg/servant-cli/pull/3
  # stellar-sdk
    - DRBG-0.5.5
  # yesod-auth-stellar
    - github: cblp/haskell-stellar-sdk
      commit: 031faeef3949af463e1a860afb1f7f907d51bc0c
